---
driver:
  name: ec2
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  ssh_key: <%= ENV['AWS_KEY_PATH'] %>

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver:
      image_id: ami-e274738a
      availability_zone: us-east-1c
      tags:
        class: iowacodecamp2015
        name: iowacodecamp2015-workstation
        removeafter: 2015-05-10
        x-created-by: smith
        x-project: iowacodecamp2015
      security_group_ids: ['sg-29d3c14c']

suites:
<%
%w[ ♣︎ ♠︎ ♥︎ ♦︎ ].each do |suit|
 %w[ A K Q J 10 9].each do |symbol| %>
  - name: <%= symbol %><%= suit %>
  <% end %>
<% end %>
